##################
# Summary: Create EC2 instance and add its IP to the hosts file
#
# Created By: Arpit Rastogi
#
- name: Launch the new EC2 Instance
  local_action: ec2
                group={{ security_group }} 
                instance_type={{ instance_type}} 
                image={{ image }} 
                wait=true
                region={{ region }} 
                keypair={{ keypair }}
                count={{count}}
  register: ec2

- set_fact:
    aws_ec2_server_instance_ids: "{{ ec2.instance_ids }}"

- name: "Tag EC2 Server"
  ec2_tag:
      region: "{{ region }}"
      resource: "{{ item }}"
      state: "{{ state }}"
      tags:
        Name: webserver
  with_items: "{{ aws_ec2_server_instance_ids }}"

- name: Add instance to group host
  add_host:
    name: "{{ item.public_dns_name }}"
    groups: "{{ grpname }}"
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"

- name: Add EC2 IP to inventoryFile
  local_action: lineinfile
                dest="./inventoryFile"
                regexp="{{ item.public_ip }}"
                insertafter="[webserver]" line="{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"
